version: '3.9'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  api-gateway:
    build: ./api-gateway
    environment:
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  auth:
    build: ./auth-microservice
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/auth
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "3001:3001"

  token-service:
    build: ./token-service
    environment:
      - PORT=3002
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - JWT_SECRET=supersecret
    depends_on:
      - rabbitmq
    ports:
      - "3002:3002"

volumes:
  mongo_data:
